version: "3.8"

services:
  nordvpn:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file:
      - docker.env
    ports:
      - 8080:8080  # qBittorrent WebUI
      - 7878:7878  # Radarr WebUI
      - 8989:8989  # Sonarr WebUI
      - 8686:8686  # Lidarr WebUI
      - 9696:9696  # Prowlarr WebUI
      - 5055:5055  # Jellyseerr WebUI
      - 7575:7575  # Homarr WebUI
    restart: unless-stopped
    networks:
      vpn:
        aliases:
          - gluetun
        ipv4_address: 192.168.100.2

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /home/alastor/.config/qbittorrent/config:/config
      - /mnt/John-Hurt/downloads:/downloads
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /home/alastor/.config/radarr/config:/config
      - /mnt/Paul-McGann/Videos/Movies:/movies
      - /mnt/John-Hurt/downloads:/downloads
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /home/alastor/.config/sonarr/config:/config
      - /mnt/John-Hurt/downloads:/downloads
      - /mnt/Paul-McGann/Videos/TV:/tv
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /home/alastor/.config/lidarr/config:/config
      - /mnt/John-Hurt/downloads:/downloads
      - /mnt/Paul-McGann/Music:/music
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /home/alastor/.config/prowlarr/config:/config
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
    restart: unless-stopped

  overseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest 
    container_name: jellyseerr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
      - PORT=5055
    volumes:
      - /home/alastor/.config/jellyseerr/config:/app/config
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /home/alastor/.config/homarr/config:/config
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
    restart: unless-stopped

networks:
  vpn:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.100.0/24"
